# ---------------------------
# KidsWords Project
# Word combinations
# Thomas Klee
# Created: 2017-12-14
# Updated: 2017-12-14
# ---------------------------

# This script analyses the co-occurence of 
# word combinations, sex and parent concern. 

library(tidyverse)
library(ggthemes)
library(RColorBrewer)

# load CDI and parent questionnaire data
# generated by 03_kidswords_dataprep.csv

# Note that read.csv function is used instead of read_csv
# to maintain variable types (eg factor, character, integer)
# defined in 02_kidswords_dataprep.R

CDIPQ <- read.csv("data/data_CDIPQ.csv") 

# select cross-sectional data for the normative study
xs <- CDIPQ %>% 
  filter(session == 1,  camos >= 16 & camos <= 30)

# test: clean up birth weights ------------------

# load messy csv file into data frame
bwdata <- read.csv("data/test_bw_data.csv")

# strip out alphabetic strings; declare as numeric; add to dataframe
lb <- as.numeric(str_extract_all(bwdata$orig_lb, "[0-9]+"))
oz <- as.numeric(str_extract_all(bwdata$orig_oz, "[0-9]+"))

# create functions to convert lb and oz to grams
grams1 <- function(x) lb*453.592
grams2 <- function(x) oz*28.35

# execute functions
grams1(lb)
grams2(oz)

# add the two results and display
bwdata$cbirth_weight <- grams1(lb) + grams2(oz)
bwdata

# remove temporary objects
rm(lb)
rm(oz)
