# ---------------------------
# KidsWords project
# Data preparation-02
# Thomas Klee
# Created: 17 Apr 2017
# Updated: 22 Apr 2017
# ---------------------------

# This script (1) defines the word lookup dataframe, 
# (2) cleans the PQ data, and (3) adds a new variable 
# for designating the session order of children who 
# participated more than once (longitudinally).

# The script requires two data files to run:
# data_CDI.csv, data_PQ.csv

# Those two files can be generated by 01_kidswords_dataprep.R
# for the purpose of anonymising the original data files and
# removing records from the website's data entry test 
# phase and the Learning to Talk project. That script hasn't 
# been uploaded to Github since it contains some participant passwords.

# load packages
library(tidyverse)
library(lubridate)

# load data from the CDI and the parent questionnaire
CDI <- read_csv("data/data_CDI.csv")
PQ <- read_csv("data/data_PQ.csv")

# load lookup table of CDI vocabulary characteristics
word_lookup<- read_csv("data/tb_CDI_word_features.csv")

# rename variables in lookup dataframe using dplyr
word_lookup <- rename(word_lookup, 
                 itemID = CDI_ItemID_CDIwf, # KidsWords item ID
                 CDI_item = CDI_Item_CDIwf, # CDI item
                 sem_field = Semantic_field_CDIwf, # semantic field of word
                 syllables = Syllables_CDIwf, # number of syllables in word
                 word_class = WordClass_CDIwf, # grammatical class of word
                 syl_structure = SylStruct_CDIwf, # syllable structure of word
                 ND = ND_CDIwf, # neighborhood density of word
                 WF = WF_CDIwf, # word frequency in English
                 WL = Length_phoneme_CDIwf, # word length in phonemes
                 IPC = IPC_CDI_wf
                 )

# replace incorrect birthdate in record 22826
CDI <- mutate(CDI, BIRTHDAY = replace(BIRTHDAY, CHILD_ID == 22826, "16-03-12"))

# locate records with missing sex (i_1_2) data in PQ dataframe
PQ[is.na(PQ$i_1_2), ]

# replace missing sex values in PQ dataframe based on values in CDI dataframe 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 20559, "Boy")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 20955, "Girl")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 21379, "Girl")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 21550, "Boy")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 21856, "Boy")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 22373, "Boy")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 22788, "Boy")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 22944, "Boy")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 23571, "Boy")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 23582, "Girl")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 24460, "Boy")) 

# locate records with missing birth order data in PQ
PQ[is.na(PQ$i_1_3), ]

# replace missing birth order values in PQ dataframe based on follow-up with parents
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 20565, "2nd")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 20955, "1st")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 20957, "1st")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 21786, "1st")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 21856, "2nd")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 22779, "1st")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 23582, "1st")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 23786, "1st")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 23884, "1st")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 23976, "1st")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 24161, "1st"))
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 24280, "4th or more")) 
# PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 22325, "")) 

# locate records with missing region data in PQ
PQ[is.na(PQ$i_1_33), ]

# replace missing region values in PQ based on follow-up with parents
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 20889, "Auckland")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 21302, "Auckland")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 21615, "Marlborough")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 21856, "Canterbury")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 22209, "Wellington")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 22660, "Otago")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 22758, "Wellington")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 23007, "Waikato")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 23395, "Auckland")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 23582, "Marlborough")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 23723, "Auckland")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 24292, "Auckland")) 

# locate records with missing twin data in PQ
PQ[is.na(PQ$i_1_7), ] %>% 
  print(n = 30)

# replace missing twin data in PQ based on follow-up with parents
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 20554, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 20583, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 20589, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 20598, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 20942, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 21001, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 21014, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 21222, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 21548, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 21856, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 22199, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 22201, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 22322, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 22628, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 22635, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 22907, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 22912, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 23259, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 23437, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 23560, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 23582, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 23682, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 23687, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 23721, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 23835, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 23976, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 24212, "no")) 

# rename two variables (character string format) 
# and define them as dates 
CDI <- rename(CDI, DOB = BIRTHDAY)
CDI$DOB <- parse_date_time(CDI$DOB, "d-m-y")
CDI <- rename(CDI, session_date = FILLEDOUT)
CDI$session_date <- parse_date_time(CDI$session_date, "d-m-y")

# create "session" variable and assign ranks to its values based session date
CDI <-
  CDI %>% group_by(CHILD_ID) %>%
  mutate(session = rank(session_date)) %>%
  arrange(CHILD_ID, session)

# declare "session" as a factor
CDI$session <- factor(CDI$session)

a <- select(CDI, CHILD_ID, DOB, session_date, session)

# done to here ----------------------------------



# test of concept -------------------------------

# Fake data creating a new variable (time) and assigning ranks based on dates
# http://stackoverflow.com/questions/29568956/how-to-add-a-rank-column-to-sorted-dates-in-r

set.seed(5)
dat = data.frame(date=sample(seq(as.Date("2015-01-01"), as.Date("2015-01-31"), 
                                 "1 day"), 12),
                 ID=rep(LETTERS[1:3], c(2,6,4)))

dat %>% group_by(ID) %>%
  mutate(wave = rank(date)) %>%
  arrange(ID, wave)

# work to be done -------------------------------

# test script for calculating age in months from a csv file

library(tidyverse)
library(lubridate)

datedata <- read_csv("datedata.csv")

mutate(datedata, agemos = round((DOE - DOB) / (365.25/12)))

# length(seq(datedata, from=DOB, to=DOE, by='month')) - 1 

# works, but not used --------------------------------

# vitals2 <- read_csv("tk_vitals.csv")

# change "date" variable (integer) into a date type
#vitals2$date <- ymd(vitals2$date)
#vitals2

#agedays <- ymd("20170406") - ymd("20170122") #works

# ----------------------------------------------------

#elapsed_months("2017-04-06", "2016-04-30")

sessionInfo()