# ---------------------------
# KidsWords project
# Data preparation-02
# Thomas Klee
# Created: 17 Apr 2017
# Updated: 14 June 2017
# ---------------------------

# This script: 
# defines the word_lookup data frame; 
# cleans the PQ data frame, renames variables and declares some as factors;
# adds a new variable to CDI data frame indicating session order of 
# cross-sectional and longitudinal data; 
# calculates child's age as a period and adds it to CDI data frame;
# calculates child's age in months as an integer and adds it.

# The script requires 3 data files: (1) data_CDI.csv and (2) data_PQ.csv 
# were generated by 01_kidswords_dataprep.R in order to anonymize the 
# original data files and remove records from the website's 
# data entry test phase and Learning to Talk project. 
# (3) tb_CDI_word_features.csv is a lookup table describing various 
# linguistic features of the CDI words.

# The script also merges the lookup and CDI data frames and creates 
# a new variable ("resp" in CDI_words) containing 1s and 0s instead of 
# "Says" and NA.

# load packages
library(tidyverse)
library(lubridate)

# load data from the CDI and the parent questionnaire
CDI <- read_csv("data/data_CDI.csv")
PQ <- read_csv("data/data_PQ.csv")

# load lookup table of CDI vocabulary characteristics
word_lookup<- read_csv("data/tb_CDI_word_features.csv")

# rename variables in lookup dataframe using dplyr
word_lookup <- rename(word_lookup, 
                 itemID = CDI_ItemID_CDIwf, # KidsWords item ID
                 CDI_item = CDI_Item_CDIwf, # CDI item
                 sem_field = Semantic_field_CDIwf, # semantic field of word
                 syllables = Syllables_CDIwf, # number of syllables in word
                 word_class = WordClass_CDIwf, # grammatical class of word
                 syl_structure = SylStruct_CDIwf, # syllable structure of word
                 ND = ND_CDIwf, # neighborhood density of word
                 WF = WF_CDIwf, # word frequency in English
                 WL = Length_phoneme_CDIwf, # word length in phonemes
                 IPC = IPC_CDI_wf
                 )

# drop unneeded variable from lookup 
word_lookup <- select(word_lookup, -Refno_CDIwf)

# replace incorrect birthdates
CDI <- mutate(CDI, BIRTHDAY = replace(BIRTHDAY, CHILD_ID == 22826, "16-03-12"))
CDI <- mutate(CDI, BIRTHDAY = replace(BIRTHDAY, CHILD_ID == 20574, "23-03-10")) # from KidsWords participants database

# locate records with missing sex (i_1_2) data in PQ dataframe
PQ[is.na(PQ$i_1_2), ]

# replace missing sex values in PQ dataframe based on values in CDI dataframe 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 20559, "Boy")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 20955, "Girl")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 21379, "Girl")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 21550, "Boy")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 21856, "Boy")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 22373, "Boy")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 22788, "Boy")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 22944, "Boy")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 23571, "Boy")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 23582, "Girl")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 24460, "Boy")) 

# locate records with missing birth order data in PQ
PQ[is.na(PQ$i_1_3), ]

# replace missing birth order values in PQ dataframe based on follow-up with parents
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 20565, "2nd")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 20955, "1st")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 20957, "1st")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 21786, "1st")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 21856, "2nd")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 22779, "1st")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 23582, "1st")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 23786, "1st")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 23884, "1st")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 23976, "1st")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 24161, "1st"))
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 24280, "4th or more")) 
# PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 22325, "")) 

# locate records with missing region data in PQ
PQ[is.na(PQ$i_1_33), ]

# replace missing region values in PQ based on follow-up with parents
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 20889, "Auckland")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 21302, "Auckland")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 21615, "Marlborough")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 21856, "Canterbury")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 22209, "Wellington")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 22660, "Otago")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 22758, "Wellington")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 23007, "Waikato")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 23395, "Auckland")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 23582, "Marlborough")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 23723, "Auckland")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 24292, "Auckland")) 

# locate records with missing twin data in PQ
PQ[is.na(PQ$i_1_7), ] %>% 
  print(n = 30)

# replace missing twin data in PQ based on follow-up with parents
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 20554, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 20583, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 20589, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 20598, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 20942, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 21001, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 21014, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 21222, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 21548, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 21856, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 22199, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 22201, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 22322, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 22628, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 22635, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 22907, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 22912, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 23259, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 23437, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 23560, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 23582, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 23682, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 23687, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 23721, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 23835, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 23976, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 24212, "no")) 

# rename two character string variables 
CDI <- rename(CDI, DOB = BIRTHDAY) 
CDI <- rename(CDI, DOS = FILLEDOUT) # date CDI was completed (session date)

# convert character strings to date class using lubridate
CDI$DOB <- dmy(CDI$DOB)
CDI$DOS <- dmy(CDI$DOS) 

# calculate interval between dates, expressed as a time span
CDI$span <- interval(CDI$DOB, CDI$DOS)

# convert interval to a period, expressed in months and days
CDI$span <- as.period(CDI$span, unit = "months")

# calculate child's age in months
# extract number of months (as an integer)
CDI$camos <- month(CDI$span)

# calculate child's age in days
CDI <- mutate(CDI, cadays = DOS - DOB)

# convert child's age in days to an integer
CDI$cadays <- as.integer(CDI$cadays)

# create "session" variable and assign ranks to its values based session date
# from http://stackoverflow.com/questions/29568956/how-to-add-a-rank-column-to-sorted-dates-in-r
CDI <-
  CDI %>% group_by(CHILD_ID) %>%
  mutate(session = rank(DOS)) %>%
  arrange(CHILD_ID, session)

# declare "session" as a factor
CDI$session <- factor(CDI$session)

# rename variables using dplyr format (new_name = current_name)
CDI <- rename(CDI, PID = CHILD_ID)
PQ <- rename(PQ,
             PID = SCL_ID,
             #            cname = i_1_1, # removed
             csex = i_1_2,
             cbirth_order = i_1_3,
             cbirth_weight_g = i_1_4,
             cbirth_weight_lb = i_1_5,
             cbirth_weight_oz = i_1_6,
             ctwin = i_1_7,
             cpremature = i_1_8,
             cprem_wks = i_1_9,
             chealth_probs = i_1_10,
             chealth_what = i_1_11,
             csiblings = i_1_12,
             cborn_in_nz = i_1_13,
             ccountry_where= i_1_14,
             ctime_in_nz = i_1_15,
             cethnicity_nz = i_1_16,
             cethnicity_other = i_1_17,
             cmain_lang = i_1_18,
             cother_langs = i_1_19,
             cwhich_langs = i_1_20,
             cdaycare = i_1_21,
             cdaycare_hrs = i_1_22,
             PQ3_hear_conc = i_1_23,
             PQ1_lang_conc = i_1_24,
             PQ2_comm_conc = i_1_25,
             why_conc = i_1_26,
             discuss_conc = i_1_27,
             #            home_phone = i_1_28, # removed
             #            cell_phone = i_1_29, # removed
             #            email_address = i_1_30, # removed
             family_hist = i_1_31,
             family_hist_who = i_1_32,
             region = i_1_33,
             #            pname = i_2_1, # removed
             prelation = i_2_2,
             pbirth_place = i_2_3,
             pother_place = i_2_4,
             parrived_nz = i_2_5,
             pethnicity_nz = i_2_6,
             pethnicity_other = i_2_7,
             psec_qual = i_2_8,
             pother_qual = i_2_9,
             pother_qual_what = i_2_10,
             poccupation = i_2_11
)

# declare some variables as nominal or ordered factors
PQ$PID <- factor(PQ$PID)
PQ$csex <- factor(PQ$csex)
PQ$cbirth_order <- ordered(PQ$cbirth_order)
PQ$ctwin <- factor(PQ$ctwin)
PQ$cpremature <- factor(PQ$cpremature)
PQ$chealth_probs <- factor(PQ$chealth_probs)
PQ$cborn_in_nz <- factor(PQ$cborn_in_nz)
PQ$ccountry_where <- factor(PQ$ccountry_where)
PQ$cethnicity_nz <- factor(PQ$cethnicity_nz)
PQ$cethnicity_other <- factor(PQ$cethnicity_other)
PQ$cmain_lang <- factor(PQ$cmain_lang)
PQ$cother_langs <- factor(PQ$cother_langs)
PQ$cmain_lang <- factor(PQ$cmain_lang)
PQ$cother_langs <- factor(PQ$cother_langs)
PQ$cdaycare <- factor(PQ$cdaycare)
PQ$PQ3_hear_conc <- factor(PQ$PQ3_hear_conc)
PQ$PQ1_lang_conc <- factor(PQ$PQ1_lang_conc)
PQ$PQ2_comm_conc <- factor(PQ$PQ2_comm_conc)
PQ$family_hist <- factor(PQ$family_hist)
PQ$region <- factor(PQ$region)
PQ$prelation <- factor(PQ$prelation)
PQ$pbirth_place <- factor(PQ$pbirth_place)
PQ$pother_place <- factor(PQ$pother_place)
PQ$pethnicity_nz <- factor(PQ$pethnicity_nz)
PQ$pethnicity_other <- factor(PQ$pethnicity_other)
PQ$psec_qual <- factor(PQ$psec_qual)

CDI$PID <- factor(CDI$PID)

# word_lookup$sem_field <- factor(word_lookup$sem_field)
word_lookup$word_class <- factor(word_lookup$word_class)
word_lookup$syl_structure <- factor(word_lookup$syl_structure)

# declare baseline (reference) category for csex
# for calculating odds ratios 
PQ$csex <- relevel(PQ$csex, "Girl")

# create 2nd data frame from CDI before converting CDI to long-format
CDI_wide <- CDI

# convert CDI data frame from wide- to long-format
CDI_long <- 
  CDI %>%
  gather(key = itemID, value = response, i_1_1:i_32_1, factor_key = TRUE)

# select variables from CDI data frames that don't also occur in PQ
CDI_long <- select(CDI_long, PID, DOB, DOS, session, camos, cadays, 
              itemID, response)
CDI_wide <- select(CDI_wide, PID, DOB, DOS, session, camos, cadays) 

# merge CDI_long and word_lookup data frames
CDI_words <- merge(CDI_long, word_lookup, by = "itemID")

# create new (duplicate) variable
CDI_words <- mutate(CDI_words, resp = response)

# recode values of new variable in order to count
# "1"s and "0"s instead of number of rows = "Says".
# Any child with no words checked on CDI will now have 
# vocabulary size correctly calculated as 0.

# recode "Says" as 1 and NA as 0
CDI_words <- CDI_words %>% replace_na(list(resp = 0))
CDI_words$resp <- recode(CDI_words$resp, Says = 1)

# CDI_words$resp[is.na(CDI_words$resp)] <- 0  # also works but not used

# delete CDI_long
rm(CDI_long)

sessionInfo()
