# ---------------------------
# KidsWords project
# Data preparation-02
# Thomas Klee
# Created: 17 Apr 2017
# Updated: 24 Apr 2017
# ---------------------------

# This script (1) defines the word lookup data frame; 
# (2) cleans the PQ data frame;
# (3) adds a new variable to CDI data frame indicating session order
# of cross-sectional and longitudinal data; and
# (4) tests and adds child age variables (in days and months) for each record.

# The script requires two data files to run:
# data_CDI.csv, data_PQ.csv

# Those two files were generated by 01_kidswords_dataprep.R
# in order to anonymize the original data files and
# removing records from the website's data entry test 
# phase and Learning to Talk project. That script hasn't 
# been uploaded to Github since it contains some confidential data.

# load packages
library(tidyverse)
library(lubridate)

# load data from the CDI and the parent questionnaire
CDI <- read_csv("data/data_CDI.csv")
PQ <- read_csv("data/data_PQ.csv")

# load lookup table of CDI vocabulary characteristics
word_lookup<- read_csv("data/tb_CDI_word_features.csv")

# rename variables in lookup dataframe using dplyr
word_lookup <- rename(word_lookup, 
                 itemID = CDI_ItemID_CDIwf, # KidsWords item ID
                 CDI_item = CDI_Item_CDIwf, # CDI item
                 sem_field = Semantic_field_CDIwf, # semantic field of word
                 syllables = Syllables_CDIwf, # number of syllables in word
                 word_class = WordClass_CDIwf, # grammatical class of word
                 syl_structure = SylStruct_CDIwf, # syllable structure of word
                 ND = ND_CDIwf, # neighborhood density of word
                 WF = WF_CDIwf, # word frequency in English
                 WL = Length_phoneme_CDIwf, # word length in phonemes
                 IPC = IPC_CDI_wf
                 )

# replace incorrect birthdates
CDI <- mutate(CDI, BIRTHDAY = replace(BIRTHDAY, CHILD_ID == 22826, "16-03-12"))
# CDI <- mutate(CDI, BIRTHDAY = replace(BIRTHDAY, CHILD_ID == 20574, "dd-mm-10")) # from KidsWords participants database

# locate records with missing sex (i_1_2) data in PQ dataframe
PQ[is.na(PQ$i_1_2), ]

# replace missing sex values in PQ dataframe based on values in CDI dataframe 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 20559, "Boy")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 20955, "Girl")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 21379, "Girl")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 21550, "Boy")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 21856, "Boy")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 22373, "Boy")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 22788, "Boy")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 22944, "Boy")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 23571, "Boy")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 23582, "Girl")) 
PQ <- mutate(PQ, i_1_2 = replace(i_1_2, SCL_ID == 24460, "Boy")) 

# locate records with missing birth order data in PQ
PQ[is.na(PQ$i_1_3), ]

# replace missing birth order values in PQ dataframe based on follow-up with parents
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 20565, "2nd")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 20955, "1st")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 20957, "1st")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 21786, "1st")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 21856, "2nd")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 22779, "1st")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 23582, "1st")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 23786, "1st")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 23884, "1st")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 23976, "1st")) 
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 24161, "1st"))
PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 24280, "4th or more")) 
# PQ <- mutate(PQ, i_1_3 = replace(i_1_3, SCL_ID == 22325, "")) 

# locate records with missing region data in PQ
PQ[is.na(PQ$i_1_33), ]

# replace missing region values in PQ based on follow-up with parents
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 20889, "Auckland")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 21302, "Auckland")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 21615, "Marlborough")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 21856, "Canterbury")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 22209, "Wellington")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 22660, "Otago")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 22758, "Wellington")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 23007, "Waikato")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 23395, "Auckland")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 23582, "Marlborough")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 23723, "Auckland")) 
PQ <- mutate(PQ, i_1_33 = replace(i_1_33, SCL_ID == 24292, "Auckland")) 

# locate records with missing twin data in PQ
PQ[is.na(PQ$i_1_7), ] %>% 
  print(n = 30)

# replace missing twin data in PQ based on follow-up with parents
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 20554, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 20583, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 20589, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 20598, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 20942, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 21001, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 21014, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 21222, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 21548, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 21856, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 22199, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 22201, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 22322, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 22628, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 22635, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 22907, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 22912, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 23259, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 23437, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 23560, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 23582, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 23682, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 23687, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 23721, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 23835, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 23976, "no")) 
PQ <- mutate(PQ, i_1_7 = replace(i_1_7, SCL_ID == 24212, "no")) 

# rename two variables (character string format) 
# and define them as dates 
CDI <- rename(CDI, DOB = BIRTHDAY)
CDI$DOB <- parse_date_time(CDI$DOB, "d-m-y")
CDI <- rename(CDI, session_date = FILLEDOUT)
CDI$session_date <- parse_date_time(CDI$session_date, "d-m-y")

# create "session" variable and assign ranks to its values based session date
# from http://stackoverflow.com/questions/29568956/how-to-add-a-rank-column-to-sorted-dates-in-r
CDI <-
  CDI %>% group_by(CHILD_ID) %>%
  mutate(session = rank(session_date)) %>%
  arrange(CHILD_ID, session)

# declare "session" as a factor
CDI$session <- factor(CDI$session)

# calculate child's age (in days)
CDI <- mutate(CDI, c_agedays = session_date - DOB)

# begin test section ============================

# several calculations were tested to
# calculate number of whole months between two dates 
# based on http://stackoverflow.com/questions/1995933/number-of-months-between-two-dates

# test 1: calculate agemos1
CDI_agetest <- mutate(CDI, agemos1 = as.numeric(floor((session_date - DOB) / (365.25/12))))
# result: age not rounded up until same day of next month reached.
# first 50 records were tested against hand calculations and all 
# new values were as expected

# test 2: calculate agemos2
# uses lubridate package
CDI_agetest$agemos2 <- interval(CDI$DOB, CDI$session_date) %/% months(1)
# result: produced identical values to test 1 (agemos1)

# test 3: calculate agemos3
elapsed_months <- function(end_date, start_date) {
  ed <- as.POSIXlt(end_date)
  sd <- as.POSIXlt(start_date)
  12 * (ed$year - sd$year) + (ed$mon - sd$mon)
}
CDI_agetest <- transform(CDI_agetest, agemos3 = elapsed_months(CDI$session_date, CDI$DOB))
# result: appears to round age to nearest month, so could be used as an alternative

# check relevant variables and their definitions and display
# note that the "AGE" variable was part of the original data file and should not be used
CDI_agetest <- select(CDI_agetest, CHILD_ID, DOB, session_date, DOB, AGE, agemos1, agemos2, agemos3, session)
CDI_agetest

# remove temporary dataframe and function
rm(CDI_agetest)
rm(elapsed_months)

# end test section ==============================

# calculate child's age (in months) without rounding to next month;
# if rounding is called for, use agemos3 variable in test section above
CDI$c_agemos <- interval(CDI$DOB, CDI$session_date) %/% months(1)

# display relevant variables and remove temp 
temp <- select(CDI, CHILD_ID, DOB, session_date, c_agemos, c_agedays, session)
temp
rm(temp)


# done to here ==================================
# code below needs further work =================

# rename some variables using dplyr format (new_name = current_name)
CDI <- rename(CDI, PID = CHILD_ID)
PQ <- rename(PQ,
             PID = SCL_ID,
             csex = i_1_2,
             cbirth_order = i_1_3,
             cbirth_weight_g = i_1_4,
             cbirth_weight_lb = i_1_5,
             cbirth_weight_oz = i_1_6,
#              = i_1_7,
             cpremature = i_1_8,
             cprem_wks= i_1_9,
#              = i_1_10,
#              = i_1_11,
#             = i_1_12,
#             = i_1_13,
#             = i_1_14,
#             = i_1_15,
#             = i_1_16,
#             = i_1_17,
#             = i_1_18,
#             = i_1_19,
#             = i_1_20,
#             = i_1_21,
#             = i_1_22,
             PQ1_lang_conc = i_1_23,
             PQ2_comm_conc = i_1_24,
             PQ3_hear_conc = i_1_25,
             why_concerned = i_1_26,
#             = i_1_27,
#             = i_1_31,
#             = i_1_32,
             region = i_1_33,
#             = i_2_2,
#             = i_2_3,
#             = i_2_4,
#             = i_2_5,
#             = i_2_6,
#             = i_2_7,
#             = i_2_8,
#             = i_2_9,
#             = i_2_10,
             occupation = i_2_11
             )

# ---------------------------
# need to convert birthweight to grams
# and create new variable: cbirthweight

# lbs_g = (cbirth_weight_lb / 2.2046)*1000
# oz_g = cbirth_weight_oz / 0.035274
# cbirthweight = lbs_g + oz_g
# ---------------------------

# declare some variables as factors
PQ$csex <- factor(PQ$csex)
PQ$cbirth_order <- factor(PQ$cbirth_order)

# convert CDI data frame from wide- to long-format # works
CDI <- 
  CDI %>%
  gather(key = CDI_item, value = measurement, i_1_1:i_32_1, factor_key = TRUE)

# drop variables not needed from CDI data frame
# since they occur in the PQ data frame
CDI <- select(CDI, PID, DOB, session_date, session, CDI_item, measurement)

# -----------------------------------------------
# needed only if calculating odds ratios 
# declare that baseline (reference) category female
# PQ$csex <- relevel(PQ$csex, "Girl")

sessionInfo()