# ---------------------------
# KidsWords Project
# Summary statistics
# Thomas Klee
# Created: 22 June 2017
# Updated: 25 June 2017
# ---------------------------

library(tidyverse)
library(xtable)

# load CDI and parent questionnaire data
# generated by 03_kidswords_dataprep.csv;
# note that read_csv function iss not used since the
# read.csv function maintains variable types (eg factor, character, integer)
# that were explicly defined earlier in 02_kidswords_dataprep.R
CDIPQ <- read.csv("data/data_CDIPQ.csv") 

# summarize demographic characteristics ---------

# for the full sample,
# tabulate sample size of each age x sex cell and add margin totals
tbl_agesex1 <- addmargins(table(CDIPQ$camos, CDIPQ$csex, dnn = c("Age", "")))
colnames(tbl_agesex1) <- c("Boys", "Girls", "n")
tbl_agesex1

# the "Age" column header gets lost when adding latex commands; otherwise ok
print(xtable(tbl_agesex1, digits = 0, align = "lrrr", caption = 'Sample size by age and sex', 
             label = "tbl:agesex1"), caption.placement = 'top', booktabs = TRUE)

# -----------------------------------------------
# select data for the cross-sectional (normative) sample
CDIPQxs <- CDIPQ %>% 
  filter(session == 1,  camos >= 16 & camos <= 30)

# tabulate size of each age x sex cell and add margin totals
tbl_agesex2 <- addmargins(table(CDIPQxs$camos, CDIPQxs$csex, dnn = c("Age", "")))
colnames(tbl_agesex2) <- c("Boys", "Girls", "n")
tbl_agesex2

# "Age" column header added above gets lost when adding latex commands; otherwise ok
print(xtable(tbl_agesex2, digits = 0, align = "lrrr", caption = 'Sample size by age and sex', 
             label = "tbl:agesex2"), caption.placement = 'top', booktabs = TRUE)

# -----------------------------------------------
# tabulate sample size by birth order and sex
bosex_counts <- table(CDIPQxs$cbirth_order, CDIPQxs$csex)
bosex_rowcounts <- rowSums(bosex_counts) # calculate row totals

# convert counts to percentages
bosex_props <- (prop.table(table(CDIPQxs$cbirth_order)) * 100)

# combine population and sample data, name columns, create latex table 
tbl_bosex <- cbind(bosex_counts, bosex_rowcounts, bosex_props)
colnames(tbl_bosex) <- c("Boys", "Girls", "Total", "%")

print(xtable(tbl_bosex,  
             digits = c(0, 0, 0, 0, 1), align = "lrrrr", 
             label = "tbl:bosex"), booktabs = TRUE)

sessionInfo()

