# ---------------------------
# KidsWords Project
# Summary statistics
# Thomas Klee
# Created: 22 June 2017
# Updated: 26 June 2017
# ---------------------------

# This script constructs some summary statistical analyses.
# R code is supplemented by LaTeX code in order that analyses 
# can be used in manuscripts etc.

library(tidyverse)
library(xtable)
library(RColorBrewer)

# load CDI and parent questionnaire data
# generated by 03_kidswords_dataprep.csv;
# note that read_csv function iss not used since the
# read.csv function maintains variable types (eg factor, character, integer)
# that were explicly defined earlier in 02_kidswords_dataprep.R
CDIPQ <- read.csv("data/data_CDIPQ.csv") 

# summarize demographic characteristics ---------

# for the full sample,
# tabulate sample size of each age x sex cell and add margin totals
tbl_agesex1 <- addmargins(table(CDIPQ$camos, CDIPQ$csex, dnn = c("Age", "")))
colnames(tbl_agesex1) <- c("Boys", "Girls", "Total")
tbl_agesex1

# the "Age" column header gets lost when adding latex commands; otherwise ok
print(xtable(tbl_agesex1, digits = 0, align = "lrrr", caption = 'Sample size by age and sex', 
             label = "tbl:agesex1"), caption.placement = 'top', booktabs = TRUE)

# -----------------------------------------------
# select data for the cross-sectional (normative) sample
CDIPQxs <- CDIPQ %>% 
  filter(session == 1,  camos >= 16 & camos <= 30)

# tabulate size of each age x sex cell and add margin totals
tbl_agesex2 <- addmargins(table(CDIPQxs$camos, CDIPQxs$csex, dnn = c("Age", "")))
colnames(tbl_agesex2) <- c("Boys", "Girls", "n")
tbl_agesex2

# "Age" column header added above gets lost when adding latex commands; otherwise ok
print(xtable(tbl_agesex2, digits = 0, align = "lrrr", caption = 'Sample size by age and sex', 
             label = "tbl:agesex2"), caption.placement = 'top', booktabs = TRUE)

# -----------------------------------------------
# tabulate sample size by birth order and sex
bosex_counts <- table(CDIPQxs$cbirth_order, CDIPQxs$csex)
bosex_rowcounts <- rowSums(bosex_counts) # calculate row totals

# convert counts to percentages
bosex_props <- (prop.table(table(CDIPQxs$cbirth_order)) * 100)

# combine population and sample data, name columns, create latex table 
tbl_bosex <- cbind(bosex_counts, bosex_rowcounts, bosex_props)
colnames(tbl_bosex) <- c("Boys", "Girls", "Total", "%")
tbl_bosex

print(xtable(tbl_bosex,  
             digits = c(0, 0, 0, 0, 1), align = "lrrrr", 
             label = "tbl:bosex"), booktabs = TRUE)

# -----------------------------------------------
# compare regional distribution of sample and NZ population
statsnz <- read_csv("data/NZBirths_20140914_NA_omit.csv")

NZbirths <- table(statsnz$region, statsnz$runAve)
NZbirths <- round((statsnz$runAve * 100), digits = 1)

# Calculate number of births per region in the KidsWords sample
region_totals <- table(CDIPQxs$region)

# Convert frequencies to percentages
region_props <- (prop.table(table(CDIPQxs$region)) * 100)

# Combine population and sample data, name columns, create latex table 
region_tbl <- with(CDIPQxs, cbind(region_totals, region_props, NZbirths))
colnames(region_tbl) <- c("n", "Sample (%)", "Population (%)")
region_tbl

print(xtable(region_tbl, digits = c(0, 0, 1, 1), align = "lrrr", 
             caption = 'Sample size by region in relation to distribution of births in the population; ignore first row for now',
             label = "tbl:regions"), caption.placement = 'top', booktabs = TRUE)

# -----------------------------------------------
# notched boxplots of CDI word total for each month
# create notched boxplot
notched_boxplot_CA <- boxplot(wordtotal ~ camos, data = CDIPQxs, 
                              notch=TRUE, col = "linen", range=1.5,
                              # main = "Vocabulary Distribution by Age", 
                              xlab = "Age in Months", ylab = "Vocabulary Size in Words")

# calculate the mean number of words for each month of age
mean_words <- aggregate(wordtotal ~ camos, CDIPQxs, mean)

# Add mean number of words per month to graph
points(mean_words$wordtotal, pch = "*")

# delete temporary data frames ------------------

rm(bosex_counts)
rm(bosex_props)
rm(tbl_agesex1)
rm(tbl_agesex2)
rm(tbl_bosex)
rm(bosex_rowcounts)
rm(region_tbl)
rm(NZbirths)
rm(region_props)
rm(region_totals)
rm(statsnz)

sessionInfo()