# ---------------------------
# KidsWords Project
# OLS and quantile regression: vocabulary
# Thomas Klee
# Created: 01 July 2017
# Updated: 06 July 2017 
# ---------------------------

# This script constructs a growth model of vocabulary development
# based on OLS regression and then quantile regression. 

library(tidyverse)
library(quantreg)
library(ggplot2)
library(ggthemes)
library(RColorBrewer)

# load CDI and parent questionnaire data
# generated by 03_kidswords_dataprep.csv

# Note that read.csv function is used instead of read_csv
# to maintain variable types (eg factor, character, integer)
# defined in 02_kidswords_dataprep.R

CDIPQ <- read.csv("data/data_CDIPQ.csv") 

# select cross-sectional data for the normative study
xs <- CDIPQ %>% 
  filter(session == 1,  camos >= 16 & camos <= 30)

# create dummy variables for regression analyses
xs$female <- if_else(xs$csex == "Girl", 1, 0)

xs$born1 <- if_else(xs$cbirth_order == "1st", 1, 0)
xs$born2 <- if_else(xs$cbirth_order == "2nd", 1, 0)
xs$born3 <- if_else(xs$cbirth_order == "3rd", 1, 0)
xs$born4 <- if_else(xs$cbirth_order == "4th or more", 1, 0)
xs$born_later <- if_else(xs$cbirth_order != "1st", 1, 0) 

xs$twin <- if_else(xs$ctwin == "yes", 1, 0)

# not used:
# define reference categories for interpreting regression analyses
# xs$csex <- relevel(xs$csex, ref = "Girl")
# xs$cbirth_order <- relevel(xs$cbirth_order, ref = "1st")
# xs$ctwin <- relevel(xs$ctwin, ref = "no")
# xs$cdaycare <- relevel(xs$cdaycare, ref = "no")
# xs$family_hist <- relevel(xs$family_hist, ref = "no")

attach(xs)

# OLS regression models -------------------------

# OLS regression using age-in-days
ols_agedays <- lm(wordtotal ~ cadays, data = xs)

summary(ols_agedays)

# OLS regression using age-in-months
ols_agemos <- lm(wordtotal ~ camos, data = xs)

summary(ols_agemos)

# plot OLS model of vocabulary and age-in-months
ggplot(xs, aes(camos, wordtotal)) +  
# geom_point(position = position_jitter(width = 1.25, height = 0)) + 
  geom_jitter(width = 0.5, height = 0.5, colour = "darkgrey") +
  geom_smooth(method = "lm",  fill = "red") +
  scale_x_continuous(breaks = seq(16,30,2),
                     name = "\nAge (months)") + 
  scale_y_continuous(breaks = seq(0,600,100),
                     name = "Vocabulary Size (words)\n") +
  ggtitle("New Zealand English", "CDI:WS") +
  theme_few() 

ggsave(file = "ols_vocab_agemos.pdf", width = 6, height = 5) # Sometimes this line needs to be run 2x to execute.

# plot OLS model of vocabulary and age-in-days
# add second x-axis to mark age-in-months for ease of reading
ggplot(xs, aes(cadays, wordtotal)) + geom_point(colour = "grey", size = 1) + 
  geom_smooth(method = "lm",  fill = "red") +
  scale_x_continuous("\nAge (days)", sec.axis = sec_axis(~ . / 30.25, breaks = seq(16, 30, 2), name ="Age (months)\n")) +
  scale_y_continuous(breaks = seq(0,600,100), name = "Vocabulary Size (words)\n") +
  ggtitle("New Zealand English", "CDI:WS") +
  theme_few() 

ggsave(file = "ols_vocab_agedays.pdf", width = 6, height = 5) # Sometimes this line needs to be run 2x to execute.

# multiple OLS regression with age + other predictors ------

# define predictor sets
y <- cbind(wordtotal)
x1 <- cbind(camos, csex, cbirth_order, ctwin)
x2 <- cbind(camos, female, born2, born3, born4, twin)
x3 <- cbind(camos, female, born_later, twin)

# descriptive statistics
summary(y)
summary(x1)
summary(x2)
summary(x3)

# multiple OLS regression with x1 predictors
ols_1 <- lm(y ~ x1, data = xs)
summary(ols_1)

# multiple OLS regression with x2 predictors
ols_2 <- lm(y ~ x2, data = xs)
summary(ols_2)
confint(ols_2)

# multiple OLS regression with x3 predictors
ols_3 <- lm(y ~ x3, data = xs)
summary(ols_3)
confint(ols_3)

# Quantile regression models --------------------

# define quantiles of interest
tau_set1 <- c(0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95)

# uses quantreg package
# linear model
# result for tau = .5 represents medial regression
qrmodel1 <- rq(y ~ x2, data = xs, tau = tau_set1)
summary(qrmodel1)

# plot coefficients from qrmodel1
qrmodel1_all <- rq(y ~ x2, data = xs, tau = seq(0.05, 0.95, by = .05))
qrmodel1_plot <- summary(qrmodel1_all)
plot(qrmodel1_plot)

# now include the born_later variable -----------
# uses quantreg package
# linear model
# result for tau = .5 represents medial regression
qrmodel2 <- rq(y ~ x3, data = xs, tau = tau_set1)
summary(qrmodel2)

# plot coefficients from qrmodel1
qrmodel2_all <- rq(y ~ x3, data = xs, tau = seq(0.05, 0.95, by = .05))
qrmodel2_plot <- summary(qrmodel2_all)
plot(qrmodel2_plot)

# Intercept plot generated above reflects default conditions:
# *uncentered* wordtotal for 1st born, singleton, males

# next step: center values so that intercept can be more easily interpreted

sessionInfo()