# ---------------------------
# KidsWords Project
# Growth curves for vocabulary
# Thomas Klee
# Created: 04 July 2017
# Updated:  
# ---------------------------

# This script constructs growth curves for vocabulary
# based on growth curve quantile regression models. 
# Vocabularly growth as a function of age is plotted, 
# with separate plots for boys, girlsand combined sexes.

library(tidyverse)
library(quantreg)
library(quantregGrowth)
library(ggthemes)
library(RColorBrewer)

# load CDI and parent questionnaire data
# generated by 03_kidswords_dataprep.csv

# Note that read.csv function is used instead of read_csv
# to maintain variable types (eg factor, character, integer)
# defined in 02_kidswords_dataprep.R

CDIPQ <- read.csv("data/data_CDIPQ.csv") 

# select cross-sectional data for the normative study
xs <- CDIPQ %>% 
  filter(session == 1,  camos >= 16 & camos <= 30)

attach(xs)

# define quantiles of interest
tau_set1 <- c(0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95)

# fit quantile curves for boys and girls combined
gcrq_comb <- gcrq(wordtotal ~ ps(camos, monotone = 1, lambda = 1000),
           data = xs, tau = tau_set1)

# select colors for quantile lines
mypalette<-brewer.pal(7,"Paired")

print(gcrq_comb, digits = 2)

plot(gcrq_comb, 
     # y = TRUE, # uncomment to add data points
     xlab = "Age (months)", 
     ylab = "Vocabulary Size (words)", 
     legend = TRUE, 
     lwd = 3, col = mypalette, lty = "solid", 
     main = "Conditional quantiles for words produced\n Combined sexes (N = 2617)\n  New Zealand English (CDI:WS)")

# fit quantile curves for boys only
xs_boys <- xs %>% 
  filter(session == 1,  camos >= 16 & camos <= 30, csex == "Boy")

gcrq_boys <- gcrq(wordtotal ~ ps(camos, monotone = 1, lambda = 1000),
           data = xs_boys, tau = tau_set1)

print(gcrq_boys, digits = 2)

plot(gcrq_boys, 
     # y = TRUE, # uncomment if data points wanted
     xlab = "Age (months)", 
     ylab = "Vocabulary Size (words)", 
     legend = TRUE,
     lwd = 3, col = mypalette, lty = "solid",
     main = "Conditional quantiles for words produced\n Boys (N = 1281)\n  New Zealand English (CDI:WS)")

# fit quantile curves for girls only
xs_girls <- xs %>% 
  filter(session == 1,  camos >= 16 & camos <= 30, csex == "Girl")

gcrq_girls <- gcrq(wordtotal ~ ps(camos, monotone = 1, lambda = 1000),
               data = xs_girls, tau = tau_set1)

print(gcrq_girls, digits = 2)

plot(gcrq_girls, 
     # y = TRUE, # uncomment if data points wanted
     xlab = "Age (months)", 
     ylab = "Vocabulary Size (words)", 
     legend = TRUE,
     lwd = 3, col = mypalette, lty = "solid",
     main = "Conditional quantiles for words produced\n Girls (N = 1336)\n  New Zealand English (CDI:WS)")

sessionInfo()