# ---------------------------
# KidsWords Project
# Modelling vocabulary with OLS and QR
# Thomas Klee
# Created: 2017-07-01
# Updated: 2017-12-12
# ---------------------------

# This script constructs growth models of vocabulary development
# based on OLS regression and then models based quantile regression,
# using the quantreg package.

library(tidyverse)
library(quantreg)
library(ggthemes)
library(RColorBrewer)

# load CDI and parent questionnaire data
# generated by 04_kidswords_dataprep.csv

# Note that read.csv function is used instead of read_csv
# to maintain variable types (eg factor, character, integer)
# defined in 02_kidswords_dataprep.R

# CDIPQ <- read.csv("data/data_CDIPQ.csv") 

# select data for CDI normative study
xs <- CDIPQ %>% 
  filter(session == 1,  camos >= 16 & camos <= 30, mono_env == "yes")

# center values of continuous predictors on the mean 
# so that intercept can be more easily interpreted;
# include new variable in xs dataframe
xs <- mutate(xs, ccamos = camos - mean(camos))

# define quantiles of interest
tau_set1 <- c(0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95)

# select colors for quantile lines
mypalette<-brewer.pal(7,"Dark2")

# -----------------------------------------------
# OLS (linear) regression model 
# -----------------------------------------------

# model 1: OLS regression of age-in-months on word total
m1 <- lm(wordtotal ~ camos, data = xs)
summary(m1)

# diagnostic plots 
layout(matrix(c(1,2,3,4),2,2)) # optional 4 graphs/page 
plot(m1)

# ggplot of OLS model (m1)
ggplot(xs, aes(camos, wordtotal)) + 
  geom_point(colour = "darkgrey") + # other options on next 2 lines
#  geom_point(position = position_jitter(width = 1.25, height = 0), colour = "darkgrey") + 
#  geom_jitter(width = 0.5, height = 0.5, colour = "darkgrey") +
  geom_smooth(method = "lm",  fill = "red") +
  scale_x_continuous(breaks = seq(16,30,2),
                     name = "\nAge (months)") + 
  scale_y_continuous(breaks = seq(0,600,100),
                     name = "Vocabulary Size (words)\n") +
  ggtitle("Linear (OLS) regression", "New Zealand CDI:WS (N = 2617)") +
  theme_few() 
ggsave(file = "m1.pdf", width = 6, height = 5) # sometimes this line needs to be run twice

# -----------------------------------------------
# Quantile regression models based on quantreg 
# -----------------------------------------------

# linear QR model
m2a <- rq(wordtotal ~ camos, data = xs, tau = tau_set1)
summary(m2a)
m2a_plot <- summary(m2a)
plot(m2a_plot) # for quantile plots of intercept and predictor

# create quantile curves using plot(), based on Koenker (2005, p. 301)
# pdf("m2a.pdf", width = 6, height = 5)  # uncomment this line to create PDF file of graph
plot(xs$camos, xs$wordtotal, cex = 0.25, type = "n",
     xlab = "Age (months)", 
     ylab = "Vocabulary Size (words)",
     las = 1,
     main = "Linear quantile regression \nNew Zealand CDI:WS (N = 2617)"
          )
points(xs$camos, xs$wordtotal, cex = 0.5, col = "darkgrey")
# abline(lm(xs$wordtotal ~ xs$camos), lty = 2, col = "red") # to add conditional mean line
for (i in 1:length(tau_set1)) {
  abline(rq(xs$wordtotal ~ xs$camos, tau = tau_set1[i]), col = "gray")
}
# dev.off()  # uncomment this line to create PDF file of graph

# repeat using ggplot's quantile regression function 
m2b <- ggplot(xs, aes(x = camos, y = wordtotal)) + 
  geom_point(colour = "darkgrey") +
  geom_quantile(quantiles = tau_set1) +
  scale_x_continuous(breaks = seq(16,30,2),
                     name = "\nAge (months)") + 
  scale_y_continuous(breaks = seq(0,700,100),
                     name = "Vocabulary Size (words)\n") +
  ggtitle("Linear quantile regression", "New Zealand CDI:WS (N = 2617)") + 
  theme_few() 
ggsave("m2b.pdf", width = 6, height = 5)

# model 1: original predictors entered, including age-in-months  
qr_m1 <- rq(wordtotal ~ camos + csex + cbirth_order + ctwin + pedcat, data = xs, tau = seq(0.05, 0.95, by = .05))
summary(qr_m1)
qr_m1_plot <- summary(qr_m1)
plot(qr_m1_plot)

# model 2: same as model 1, but age has been centered on its mean  
qr_m2 <- rq(wordtotal ~ ccamos + csex + cbirth_order + ctwin + pedcat, data = xs, tau = seq(0.05, 0.95, by = .05))
summary(qr_m2)
qr_m2_plot <- summary(qr_m2)
plot(qr_m2_plot)

# create dummy variables for regression analyses
xs$male <- if_else(xs$csex == "Boy", 1, 0)
# xs$born1 <- if_else(xs$cbirth_order == "1st", 1, 0)
xs$born_later <- if_else(xs$cbirth_order != "1st", 1, 0) 
xs$twin <- if_else(xs$ctwin == "yes", 1, 0)
xs$noqual <- if_else(xs$pedcat == "0", 1, 0)

# reference case for model 3 based on 1st born girl, singleton with  
# mother having at least a high school qualification;
# age-in-months is entered to predict vocabulary size

# model 3: same as model 1, but predictors converted to dichotomous variables before being entered
qr_m3 <- rq(wordtotal ~ camos + male + born_later + twin + noqual, data = xs, tau = seq(0.05, 0.95, by = .05))
summary(qr_m3)
qr_m3_plot <- summary(qr_m3)
plot(qr_m3_plot)

# reference case for model 4 based on 1st born girl, singleton with  
# mother having at least a high school qualification;
# age-in-months has been centered on its mean

# model 4: same as model 2, with age centered on its mean
# for easier interpretation of the intercept
qr_m4 <- rq(wordtotal ~ ccamos + male + born_later + twin + noqual, data = xs, tau = seq(0.05, 0.95, by = .05))
summary(qr_m4)
qr_m4_plot <- summary(qr_m4)
plot(qr_m4_plot)

sessionInfo()