# ---------------------------
# KidsWords Project
# Word combinations
# Thomas Klee
# Created: 2017-12-12
# Updated: 2017-12-12
# ---------------------------

# This script analyses reported use of word combinations
# as a function of age, sex and other variables.

library(tidyverse)
library(ggthemes)
library(RColorBrewer)

# load CDI and parent questionnaire data
# generated by 03_kidswords_dataprep.csv

# Note that read.csv function is used instead of read_csv
# to maintain variable types (eg factor, character, integer)
# defined in 02_kidswords_dataprep.R

CDIPQ <- read.csv("data/data_CDIPQ.csv") 

# select cross-sectional data for the normative study
xs <- CDIPQ %>% 
  filter(session == 1,  camos >= 16 & camos <= 30)

# declare wc variable as a factor
xs$CDI_wc <- as.factor(xs$CDI_wc)

# create new wc variable with labels
xs$wc <- recode_factor(xs$CDI_wc, '0' = "Not yet", '1' = "Sometimes", '2' = "Often")

# calculate proportion of each wc category at each age
dfwc <- xs %>%
  group_by(camos) %>%
  count(wc) %>%
  mutate(prop_wc = prop.table(n))
  
# plot proportions across age range
ggplot(dfwc, aes(x = camos, y = prop_wc, fill = wc)) + geom_bar(stat = "identity") +
  labs(x = "Age (months)", y = "Proportion", title = "Reported word combinations on NZ CDI") +
  facet_grid(wc ~ .) +
  theme_hc()

sessionInfo()