# ---------------------------
# KidsWords Project
# Modelling vocabulary size with OLS and QR
# Thomas Klee
# Created: 2019-11-22
# Updated: 2019-11-26
# ---------------------------

# This script constructs growth models of vocabulary size
# from demographic variables
# using OLS and quantile regression.

library(tidyverse)
library(quantreg)

# load CDI and parent questionnaire data
# generated by 04_kidswords_dataprep.csv

# Note that read.csv function is used instead of read_csv
# to maintain variable types (eg factor, character, integer)
# defined in 02_kidswords_dataprep.R

CDIPQ <- read.csv("data/data_CDIPQ.csv") 

# select data for CDI normative study
xs <- CDIPQ %>% 
  filter(session == 1,  camos >= 16 & camos <= 30, mono_env == "yes")

# center values of age (camos) on its mean 
# so that model intercept can be more easily interpreted;
# add new variable (ccamos) to data frame
xs <- mutate(xs, ccamos = camos - mean(camos))

# define parent education as a factor
xs$pedcat <- factor(xs$pedcat)

# based on similarity of pedcat means, dichotomize pedcat
# into 'qualification' or 'no qualification'
# and define new variable as a factor
xs$pedcat2 <- factor(ifelse(xs$pedcat == "0", "noqual", "qual"))

# declare baseline (reference) categories
# for regression analyses
xs$csex <- relevel(xs$csex, "Girl")
xs$cbirth_order <- relevel(xs$cbirth_order, "1st")
xs$ctwin <- relevel(xs$ctwin, "no")
xs$pedcat2 <- relevel(xs$pedcat2, "qual")

# -----------------------------------------------
# OLS regression models
# -----------------------------------------------

# OLS model 1: age-in-months on word total ------
m1 <- lm(wordtotal ~ ccamos, data = xs)
summary(m1)
confint(m1)

# diagnostic plots 
layout(matrix(c(1,2,3,4),2,2)) # optional 4 graphs/page 
plot(m1)

# OLS model 2: age and sex ----------------------
m2 <- lm(wordtotal ~ ccamos + csex, data = xs)
summary(m2)
confint(m2)

# diagnostic plots 
layout(matrix(c(1,2,3,4),2,2)) # optional 4 graphs/page 
plot(m2)

# OLS model 3: age, sex, other variables --------
m3<- lm(wordtotal ~ ccamos + csex + cbirth_order + ctwin + pedcat2, data = xs)
summary(m3)
confint(m3)

# diagnostic plots 
layout(matrix(c(1,2,3,4),2,2)) # optional 4 graphs/page 
plot(m3)

# -----------------------------------------------
# QR model 
# -----------------------------------------------

# model 4: reference case based on 1st born, singleton girl 
# whose mother has an educational qualification:
# best quess in terms of protective factors.

# create table for manuscript: QR coefficients at 3 quantiles
m4 <- rq(wordtotal ~ ccamos + csex + cbirth_order + ctwin + pedcat2, data = xs, tau = c(0.1, 0.5, 0.9))
summary(m4)

# create figure for manuscript: plot QR coefficients and 95% CIs
m4_coeff <- rq(wordtotal ~ ccamos + csex + cbirth_order + ctwin + pedcat2, data = xs, tau = seq(0.05, 0.95, by = .05))
summary(m4_coeff)
m4_coeff_plot <- summary(m4_coeff)
plot(m4_coeff_plot)

# print confidence intervals of QR coefficients
summary(m4, se = "rank")

# Notes about the confidence intervals used here:

# For sample sizes under about 1000, quantreg's summary(x) function can be used to generate
# confidence interals (see Koenker, 2005, p. 298). However, with our large sample, standard
# errors were produced in the output. To get around this, the function above was used. 

# From quantreg's help page for summary.rq:
# se = "rank" was used since ... it produces confidence intervals for the estimated parameters 
# by inverting a rank test as described in Koenker (1994). This method involves solving a 
# parametric linear programming problem, and for large sample sizes can be extremely slow, 
# so by default it is only used when the sample size is less than 1000, see below. 

sessionInfo()
